### ISSUE TITLE
v1.4.3 package unavailable?

### ISSUE THREAD

**Issue by petertuharsky** [Wolvverine/protocolsmanager#8]
Hallo,

I am interested in downloading the Protocolsmanager plugin.
According to the homepage, there should be package v1.4.3 available compatible with GLPI 10. However, I don't see it on the Releases page https://github.com/mateusznitka/protocolsmanager/releases

How could I get it, please?

**Comment by petertuharsky** [comment]
All right, I found the other fork at https://github.com/CanMik/protocolsmanager

**Comment by Wolvverine** [comment]
All code are  compatible with GLPI 10+ in this repository master branch.
